config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tasks#index'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, length: { maximum: 30 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
  	root_path
  end

  def after_sign_out_path_for(resource)
  	new_user_password_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_task, only: [:edit]
  def new
  	@task = Task.new
  end

  def create
  	@task = Task.new(task_params)
  	@task.user_id = current_user.id
  	if @task.save
  	  redirect_to tasks_path, notice: "success to #{@task.name}"
  	else
  	  render :new
  	end
  end

  def index
  	@tasks = current_user.tasks
  end

  def show
  	@task = Task.find(params[:id])
  end

  def edit
  	@task = Task.find(params[:id])
  	if current_user != @task.user_id
  	  redirect_to tasks_path
  	end
  end

  private

  def task_params
  	params.require(:task).permit(:name, :description)
  end

  def ensure_correct_task
  	@task = Task.find(params[:id])
  	unless @task.user == current_user
  	  redirect_to tasks_path
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SystemSpec</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash.notice.present? %>
      <div class="alert">
        <p class="flash"><%= notice %></p>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

app/views/tasks/index.html.erb
<h1>tasks index</h1>

<%= link_to 'Log_out', destroy_user_session_path, method: :delete %>

<% @tasks.each do |task| %>
  <%= task.name %>
  <%= task.description %>
  <%= link_to 'Show', task_path(task) %>
<% end %>

<%= link_to 'New', new_task_path, class: 'btn btn-primary' %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<% if @task.errors.present? %>
  <ul id="error_explanation">
    <% @task.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @task, local: true do |f| %>
  <div class="form-group">
  	<%= f.label :name, '名称' %>
  	<%= f.text_field :name, class: 'form-control', id: 'task_name' %>
  </div>
  <div class="form-group">
  	<%= f.label :description %>
  	<%= f.text_area :description, class: 'form-control', id: 'task_description' %>
  </div>
  <div class="submit">
  	<%= f.submit '登録する' %>
  </div>
<% end %>

app/views/tasks/show.html.erb
<h1>Show Task</h1>

<%= @task.name %>
<%= @task.description %>

<%= link_to 'Edit', edit_task_path(@task) %>